### ISSUE TITLE
Images Not Loading

### ISSUE THREAD

**Issue by RedSalsicha** [eruecco87/PokemonGoBot-RocketTheme#14]
Images Not Loading in RocketTheme =/

**Comment by erikauer** [comment]
<img width="829" alt="screen shot 2016-08-13 at 23 42 01" src="https://cloud.githubusercontent.com/assets/8037110/17645781/9eee3ff8-61af-11e6-90ad-9419b0279c9f.png">

When you open the image you see that hotlinking is not allowed. Let me check.

Edit: We can change the link to: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png

Then it should work properly. I think this is the easiest solutions to fix this problem. I can do it... just a mom

**Comment by erikauer** [comment]
I forgot to do the same for the popups. So I will change the link in the notification module too. This will display the pokemon image properly again.
