### ISSUE TITLE
Broken Image Links

### ISSUE THREAD

**Issue by Mixone-FinallyHere** [eruecco87/PokemonGoBot-RocketTheme#21]
I see in your code you have already changed it, but it is not working in the gh page, I had to overwrite your whole main function to get the images.

Is it an error or you just haven't uploaded the latest build?

Thanks for the work you put into this :D

**Comment by adaur** [comment]
Same here, the images do not work

**Comment by eruecco87-zz** [comment]
This has been fixed in a previous pull request
