### ISSUE TITLE
Link of images in map module should be change to match pokebank module

### ISSUE THREAD

**Issue by stupiz** [eruecco87/PokemonGoBot-RocketTheme#22]
Pokemon doesn't show on map, I saw previous committed link of pokemon sprite changed but in the map module still be the old one.

**Comment by erikauer** [comment]
#17 will fix this too. In this pr i changed the link in map module and in the popup as well.

**Comment by eruecco87-zz** [comment]
Yes, the PR by @erikauer took care of it. Thanks for that! :)
