### ISSUE TITLE
RocketTheme : Pokemon Picture is not shown on UI.

### ISSUE THREAD

**Issue by nuttikung** [eruecco87/PokemonGoBot-RocketTheme#26]
**Description:**
Pokemon on (http://ui.pogobot.club/RocketTheme) is not shown correctly

**Steps to reproduce:**
Prerequisite : 
-Start your bot with web socket (https://github.com/jabbink/PokemonGoBot)
-Your bot is working fine.
1. Login to UI on (http://ui.pogobot.club/RocketTheme)
2. Verify Pokemon Pictures are shown correctly.

**Expected behavior:**
All pictures are shown correctly.

**Actual behavior:**
Pokemon Pictures are not shown correctly.

**Work Around**
Open datasource (Picture by yourself and verify on rocket theme console It will be shown correctly)

**Stacktrace (If it's a crash):**
http://pastebin.com/raw/faQ00U2z

**Version:**
Don't know (If bot I use version 0.6.0)

**Operating System:**
OSX El Capitan 10.11.6

**Java version:**
JDK 1.8.0_101

Result After Login Success.
<img width="400" alt="pokemon_pic_not_show" src="https://cloud.githubusercontent.com/assets/8456620/17894868/35edc3fc-6975-11e6-87c0-1de7ed71bb50.png">

This is screenshot to confirm after I ran workaround.
<img width="398" alt="after_workaround" src="https://cloud.githubusercontent.com/assets/8456620/17894866/352ff44e-6975-11e6-9a68-d8d1e87f7958.png">
Screen Shot _01
<img width="398" alt="after_workaround_2" src="https://cloud.githubusercontent.com/assets/8456620/17895271/c648b730-6976-11e6-98f9-7e0cbd9ae362.png">
Screen Shot _02

**Comment by KingMatt123** [comment]
I have the same issue as well :'(

**Comment by eruecco87-zz** [comment]
This has been fixed in a previous pull request
